config/routes.rb
Rails.application.routes.draw do

  resources :lancamentos
  resources :nf_vendas
  resources :fichas
  resources :bancos
  resources :vendedors
  resources :meio_pagamentos
  resources :customers
  resources :cars
  resources :locals
  resources :sessions, only: [:new, :create, :destroy]
  
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  
  resources :users
  get 'page/index'

  root 'sessions#new'

end

app/models/banco.rb
class Banco < ActiveRecord::Base
    validates :nome, presence: true
end

app/models/car.rb
class Car < ActiveRecord::Base
  belongs_to :local
  
  validates :placa, presence: true
  validates :local, presence: true
  validates :modelo, presence: true
  validates :combustivel, presence: true
  validates :anofabricacao, presence: true
  validates :anomodelo, presence: true
  validates :km, presence: true
  validates :valorvenda, presence: true
end

app/models/customer.rb
class Customer < ActiveRecord::Base
    
    validates :nome, presence: true
    validates :telefone, presence: true
    validates :endereco, presence: true
    validates :cpfcnpj, presence: true
    validates :clioufor, presence: true
    validates :email, presence: true
end

app/models/ficha.rb
class Ficha < ActiveRecord::Base
  belongs_to :Vendedor
  belongs_to :Banco
  belongs_to :Customer
  belongs_to :Cars
  belongs_to :MeioPagamento
  
  validates :Vendedor, presence: true
  validates :Banco, presence: true
  validates :Customer, presence: true
  validates :Cars, presence: true
  validates :MeioPagamento, presence: true
  validates :coef, presence: true
  validates :valfinanceiro, presence: true
  validates :valorparcela, presence: true
  validates :valortotal, presence: true
end

app/models/lancamento.rb
class Lancamento < ActiveRecord::Base
  belongs_to :Ficha
  belongs_to :Customer
  
  validates :status, presence: true
  validates :Customer_id, presence: true
  validates :dtemissao, presence: true
  validates :dtvencimento, presence: true
  validates :valor, presence: true
end

app/models/local.rb
class Local < ActiveRecord::Base
    validates :descricao, presence: true
end

app/models/meio_pagamento.rb
class MeioPagamento < ActiveRecord::Base
    validates :numparcelas, presence: true
    validates :tipo, presence: true
    validates :descricao, presence: true
end

app/models/nf_venda.rb
class NfVenda < ActiveRecord::Base
  belongs_to :Ficha
  
  validates :numerodocumento, presence: true
  validates :valor, presence: true
  validates :desconto, presence: true
  validates :acrescimo, presence: true
  
  
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates :name, 
            presence: true
            
  validates :email, 
            presence: true,
            uniqueness: true, 
            format:{
                with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i
            }

  validates :password, :presence => true,
                   :confirmation => true,
                   :length => {:within => 6..40}
  
end

app/models/vendedor.rb
class Vendedor < ActiveRecord::Base
    validates :nome, presence: true
end

app/controllers/nf_vendas_controller.rb
class NfVendasController < ApplicationController
  before_action :set_nf_venda, only: [:show, :edit, :update, :destroy]

  # GET /nf_vendas
  def index
    check_user
    @nf_vendas = NfVenda.all
  end

  # GET /nf_vendas/1
  def show
    check_user
  end

  # GET /nf_vendas/new
  def new
    check_user
    @nf_venda = NfVenda.new
  end

  # GET /nf_vendas/1/edit
  def edit
    check_user
  end

  # POST /nf_vendas
  def create
    @nf_venda = NfVenda.new(nf_venda_params)

    if @nf_venda.save
      redirect_to @nf_venda, notice: 'Nf venda was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /nf_vendas/1
  def update
    if @nf_venda.update(nf_venda_params)
      redirect_to @nf_venda, notice: 'Nf venda was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /nf_vendas/1
  def destroy
    @nf_venda.destroy
    redirect_to nf_vendas_url, notice: 'Nf venda was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_nf_venda
      @nf_venda = NfVenda.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def nf_venda_params
      params.require(:nf_venda).permit(:numerodocumento, :valor, :desconto, :acrescimo, :Ficha_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bancos_helper.rb
module BancosHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/fichas_helper.rb
module FichasHelper
end

app/helpers/lancamentos_helper.rb
module LancamentosHelper
end

app/helpers/locals_helper.rb
module LocalsHelper
end

app/helpers/nf_vendas_helper.rb
module NfVendasHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/vendedors_helper.rb
module VendedorsHelper
end

app/views/nf_vendas/_form.html.erb
<%= form_for(@nf_venda) do |f| %>
  <% if @nf_venda.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@nf_venda.errors.count, "error") %> prohibited this nf_venda from being saved:</h2>

      <ul>
      <% @nf_venda.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :numerodocumento %><br>
    <%= f.text_field :numerodocumento %>
  </div>
  <div class="field">
    <%= f.label :valor %><br>
    <%= f.text_field :valor %>
  </div>
  <div class="field">
    <%= f.label :desconto %><br>
    <%= f.text_field :desconto %>
  </div>
  <div class="field">
    <%= f.label :acrescimo %><br>
    <%= f.text_field :acrescimo %>
  </div>
  <div class="field">
    <%= f.label :Ficha_id %><br>
    <%= f.text_field :Ficha_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/nf_vendas/edit.html.erb
<h1>Editing Nf Venda</h1>

<%= render 'form' %>

<%= link_to 'Show', @nf_venda %> |
<%= link_to 'Back', nf_vendas_path %>

app/views/nf_vendas/index.html.erb
<div class="header">
<h1>Nf Vendas</h1>
</div>
<table id="t01">
  <thead>
    <%= stylesheet_link_tag  'scaffolds', media: 'all', 'data-turbolinks-track' => true %>
    <p id="notice"><%= notice %></p>
    <tr>
      <th>Numerodocumento</th>
      <th>Valor</th>
      <th>Desconto</th>
      <th>Acrescimo</th>
      <th>Ficha</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @nf_vendas.each do |nf_venda| %>
      <tr>
        <td><%= nf_venda.numerodocumento %></td>
        <td><%= nf_venda.valor %></td>
        <td><%= nf_venda.desconto %></td>
        <td><%= nf_venda.acrescimo %></td>
        <td><%= nf_venda.Ficha_id %></td>
        <td><%= link_to 'Show', nf_venda %></td>
        <td><%= link_to 'Edit', edit_nf_venda_path(nf_venda) %></td>
        <td><%= link_to 'Destroy', nf_venda, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to t('New')+' Nf venda', new_nf_venda_path %>

app/views/nf_vendas/new.html.erb
<html>
	<head>
		<%= stylesheet_link_tag  'scaffolds', media: 'all', 'data-turbolinks-track' => true %>
	</head>
	<body>
		<div class="header">
			<h1>Nova Nf-Venda</h1>
		</div>

<%= render 'form' %>

<%= link_to 'Back', nf_vendas_path %>
</body>
</html>

app/views/nf_vendas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Numerodocumento:</strong>
  <%= @nf_venda.numerodocumento %>
</p>

<p>
  <strong>Valor:</strong>
  <%= @nf_venda.valor %>
</p>

<p>
  <strong>Desconto:</strong>
  <%= @nf_venda.desconto %>
</p>

<p>
  <strong>Acrescimo:</strong>
  <%= @nf_venda.acrescimo %>
</p>

<p>
  <strong>Ficha:</strong>
  <%= @nf_venda.Ficha %>
</p>

<%= link_to 'Edit', edit_nf_venda_path(@nf_venda) %> |
<%= link_to 'Back', nf_vendas_path %>