config/routes.rb
Rails.application.routes.draw do

  resources :lancamentos
  resources :nf_vendas
  resources :fichas
  resources :bancos
  resources :vendedors
  resources :meio_pagamentos
  resources :customers
  resources :cars
  resources :locals
  resources :sessions, only: [:new, :create, :destroy]
  
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  
  resources :users
  get 'page/index'

  root 'sessions#new'

end

app/models/banco.rb
class Banco < ActiveRecord::Base
    validates :nome, presence: true
end

app/models/car.rb
class Car < ActiveRecord::Base
  belongs_to :local
  
  validates :placa, presence: true
  validates :local, presence: true
  validates :modelo, presence: true
  validates :combustivel, presence: true
  validates :anofabricacao, presence: true
  validates :anomodelo, presence: true
  validates :km, presence: true
  validates :valorvenda, presence: true
end

app/models/customer.rb
class Customer < ActiveRecord::Base
    
    validates :nome, presence: true
    validates :telefone, presence: true
    validates :endereco, presence: true
    validates :cpfcnpj, presence: true
    validates :clioufor, presence: true
    validates :email, presence: true
end

app/models/ficha.rb
class Ficha < ActiveRecord::Base
  belongs_to :Vendedor
  belongs_to :Banco
  belongs_to :Customer
  belongs_to :Cars
  belongs_to :MeioPagamento
  
  validates :Vendedor, presence: true
  validates :Banco, presence: true
  validates :Customer, presence: true
  validates :Cars, presence: true
  validates :MeioPagamento, presence: true
  validates :coef, presence: true
  validates :valfinanceiro, presence: true
  validates :valorparcela, presence: true
  validates :valortotal, presence: true
end

app/models/lancamento.rb
class Lancamento < ActiveRecord::Base
  belongs_to :Ficha
  belongs_to :Customer
  
  validates :status, presence: true
  validates :Customer_id, presence: true
  validates :dtemissao, presence: true
  validates :dtvencimento, presence: true
  validates :valor, presence: true
end

app/models/local.rb
class Local < ActiveRecord::Base
    validates :descricao, presence: true
end

app/models/meio_pagamento.rb
class MeioPagamento < ActiveRecord::Base
    validates :numparcelas, presence: true
    validates :tipo, presence: true
    validates :descricao, presence: true
end

app/models/nf_venda.rb
class NfVenda < ActiveRecord::Base
  belongs_to :Ficha
  
  validates :numerodocumento, presence: true
  validates :valor, presence: true
  validates :desconto, presence: true
  validates :acrescimo, presence: true
  
  
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates :name, 
            presence: true
            
  validates :email, 
            presence: true,
            uniqueness: true, 
            format:{
                with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i
            }

  validates :password, :presence => true,
                   :confirmation => true,
                   :length => {:within => 6..40}
  
end

app/models/vendedor.rb
class Vendedor < ActiveRecord::Base
    validates :nome, presence: true
end

app/controllers/fichas_controller.rb
class FichasController < ApplicationController
  before_action :set_ficha, only: [:show, :edit, :update, :destroy]

  # GET /fichas
  def index
    check_user
    @fichas = Ficha.all
  end

  # GET /fichas/1
  def show
    @ficha = Ficha.all.find(params[:id])
    check_user
  end

  # GET /fichas/new
  def new
    check_user
    @ficha = Ficha.new

    if params.has_key?(:carro)
      carro = Car.find(params[:carro]) 
      @ficha.Cars_id = carro.id
      @ficha.valfinanceiro = carro.valorvenda
      @ficha.valortotal = carro.valorvenda
    end
    
  end
  

  # GET /fichas/1/edit
  def edit
    @ficha = Ficha.all.find(params[:id])
    check_user
  end

  # POST /fichas
  def create
    @ficha = Ficha.new(ficha_params)

    if @ficha.save
      redirect_to @ficha, notice: 'Ficha was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /fichas/1
  def update
    if @ficha.update(ficha_params)
      redirect_to @ficha, notice: 'Ficha was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /fichas/1
  def destroy
    @ficha.destroy
    redirect_to fichas_url, notice: 'Ficha was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ficha
      @ficha = Ficha.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def ficha_params
      params.require(:ficha).permit(:data, :Vendedor_id, :Banco_id, :tipopfin, :coef, :valfinanceiro, :numparcelas, :valorparcela, :valortotal, :Customer_id, :Cars_id, :MeioPagamento_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bancos_helper.rb
module BancosHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/fichas_helper.rb
module FichasHelper
end

app/helpers/lancamentos_helper.rb
module LancamentosHelper
end

app/helpers/locals_helper.rb
module LocalsHelper
end

app/helpers/nf_vendas_helper.rb
module NfVendasHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/vendedors_helper.rb
module VendedorsHelper
end

app/views/fichas/_form.html.erb
<%= form_for(@ficha) do |f| %>
  <% if @ficha.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ficha.errors.count, "error") %> prohibited this ficha from being saved:</h2>

      <ul>
      <% @ficha.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :data %><br>
    <%= f.date_select :data %>
  </div>
  <div class="field">
    <%= f.label :Vendedor_id %><br>
    <%= f.select(:Vendedor_id, Vendedor.all.collect {|p| [ p.nome, p.id ] }, {include_blank: 'Não Definido'})%>
  </div>
  <div class="field">
    <%= f.label :Banco_id %><br>
        <%= f.select(:Banco_id, Banco.all.collect {|p| [ p.nome, p.id ] }, {include_blank: 'Não Definido'})%>
  </div>
  <div class="field">
    <%= f.label :tipopfin %><br>
    <%= f.select(:tipopfin, options_for_select([["Venda","0"], ["Compra","1"]]))%>
  </div>
  <div class="field">
    <%= f.label :coef %><br>
    <%= f.text_field :coef %>
  </div>
  <div class="field">
    <%= f.label :valfinanceiro %><br>
    <%= f.text_field :valfinanceiro %>
  </div>
  <div class="field">
    <%= f.label :numparcelas %><br>
    <%= f.text_field :numparcelas %>
  </div>
  <div class="field">
    <%= f.label :valorparcela %><br>
    <%= f.text_field :valorparcela %>
  </div>
  <div class="field">
    <%= f.label :valortotal %><br>
    <%= f.text_field :valortotal %>
  </div>
  <div class="field">
    <%= f.label :Customer_id %><br>
    <%= f.select(:Customer_id, Customer.all.collect {|p| [ p.nome, p.id ] }, {include_blank: 'Não Definido'})%>
  </div>
  <div class="field">
    <%= f.label :Cars_id %><br>
    <%= f.select(:Cars_id, Car.all.collect {|p| [ p.modelo, p.id ] }, {include_blank: 'Não Definido'})%>
  </div>
  <div class="field">
    <%= f.label :MeioPagamento_id %><br>
    <%= f.select(:MeioPagamento_id, MeioPagamento.all.collect {|p| [ p.descricao, p.id ] }, {include_blank: 'Não Definido'})%>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/fichas/edit.html.erb
<h1>Editing Ficha</h1>

<%= render 'form' %>

<%= link_to 'Show', @ficha %> |
<%= link_to 'Back', fichas_path %>

app/views/fichas/index.html.erb
<div class="header">
<h1>Fichas</h1>
</div>
<table id="t01">
  <thead>
    <%= stylesheet_link_tag  'scaffolds', media: 'all', 'data-turbolinks-track' => true %>
    <tr>
      <br/>
      <th>Data</th>
      <th>Vendedor</th>
      <th>Banco</th>
      <th>Tipopfin</th>
      <th>Coef</th>
      <th>Valfinanceiro</th>
      <th>Numparcelas</th>
      <th>Valorparcela</th>
      <th>Valortotal</th>
      <th>Customer</th>
      <th>Cars</th>
      <th>Meiopagamento</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @fichas.each do |ficha| %>
      <tr>
        <td><%= ficha.data %></td>
        <td><%= ficha.Vendedor.nome %></td>
        <td><%= ficha.Banco.nome %></td>
        <td><%= ficha.tipopfin %></td>
        <td><%= ficha.coef %></td>
        <td><%= ficha.valfinanceiro %></td>
        <td><%= ficha.numparcelas %></td>
        <td><%= ficha.valorparcela %></td>
        <td><%= ficha.valortotal %></td>
        <td><%= ficha.Customer.nome%></td>
        <td><%= ficha.Cars_id %></td>
        <td><%= ficha.MeioPagamento_id %></td>
        <td><%= link_to 'Show', ficha %></td>
        <td><%= link_to 'Edit', edit_ficha_path(ficha) %></td>
        <td><%= link_to 'Destroy', ficha, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ficha', new_ficha_path %>

app/views/fichas/new.html.erb
<html>
	<head>
		<%= stylesheet_link_tag  'scaffolds', media: 'all', 'data-turbolinks-track' => true %>
	</head>
	<body>
		<div class="header">
	<h1>New Ficha</h1>
</div>

	</body>
<%= render 'form' %>

<%= link_to 'Back', fichas_path %>
</html>

app/views/fichas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Data:</strong>
  <%= @ficha.data %>
</p>

<p>
  <strong>Vendedor:</strong>
  <%= @ficha.Vendedor %>
</p>

<p>
  <strong>Banco:</strong>
  <%= @ficha.Banco %>
</p>

<p>
  <strong>Tipopfin:</strong>
  <%= @ficha.tipopfin %>
</p>

<p>
  <strong>Coef:</strong>
  <%= @ficha.coef %>
</p>

<p>
  <strong>Valfinanceiro:</strong>
  <%= @ficha.valfinanceiro %>
</p>

<p>
  <strong>Numparcelas:</strong>
  <%= @ficha.numparcelas %>
</p>

<p>
  <strong>Valorparcela:</strong>
  <%= @ficha.valorparcela %>
</p>

<p>
  <strong>Valortotal:</strong>
  <%= @ficha.valortotal %>
</p>

<p>
  <strong>Customer:</strong>
  <%= @ficha.Customer %>
</p>

<p>
  <strong>Cars:</strong>
  <%= @ficha.Cars_id %>
</p>

<p>
  <strong>Meiopagamento:</strong>
  <%= @ficha.MeioPagamento_id %>
</p>

<%= link_to 'Edit', edit_ficha_path(@ficha) %> |
<%= link_to 'Back', fichas_path %>