config/routes.rb
Rails.application.routes.draw do

  resources :lancamentos
  resources :nf_vendas
  resources :fichas
  resources :bancos
  resources :vendedors
  resources :meio_pagamentos
  resources :customers
  resources :cars
  resources :locals
  resources :sessions, only: [:new, :create, :destroy]
  
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  
  resources :users
  get 'page/index'

  root 'sessions#new'

end

app/models/banco.rb
class Banco < ActiveRecord::Base
    validates :nome, presence: true
end

app/models/car.rb
class Car < ActiveRecord::Base
  belongs_to :local
  
  validates :placa, presence: true
  validates :local, presence: true
  validates :modelo, presence: true
  validates :combustivel, presence: true
  validates :anofabricacao, presence: true
  validates :anomodelo, presence: true
  validates :km, presence: true
  validates :valorvenda, presence: true
end

app/models/customer.rb
class Customer < ActiveRecord::Base
    
    validates :nome, presence: true
    validates :telefone, presence: true
    validates :endereco, presence: true
    validates :cpfcnpj, presence: true
    validates :clioufor, presence: true
    validates :email, presence: true
end

app/models/ficha.rb
class Ficha < ActiveRecord::Base
  belongs_to :Vendedor
  belongs_to :Banco
  belongs_to :Customer
  belongs_to :Cars
  belongs_to :MeioPagamento
  
  validates :Vendedor, presence: true
  validates :Banco, presence: true
  validates :Customer, presence: true
  validates :Cars, presence: true
  validates :MeioPagamento, presence: true
  validates :coef, presence: true
  validates :valfinanceiro, presence: true
  validates :valorparcela, presence: true
  validates :valortotal, presence: true
end

app/models/lancamento.rb
class Lancamento < ActiveRecord::Base
  belongs_to :Ficha
  belongs_to :Customer
  
  validates :status, presence: true
  validates :Customer_id, presence: true
  validates :dtemissao, presence: true
  validates :dtvencimento, presence: true
  validates :valor, presence: true
end

app/models/local.rb
class Local < ActiveRecord::Base
    validates :descricao, presence: true
end

app/models/meio_pagamento.rb
class MeioPagamento < ActiveRecord::Base
    validates :numparcelas, presence: true
    validates :tipo, presence: true
    validates :descricao, presence: true
end

app/models/nf_venda.rb
class NfVenda < ActiveRecord::Base
  belongs_to :Ficha
  
  validates :numerodocumento, presence: true
  validates :valor, presence: true
  validates :desconto, presence: true
  validates :acrescimo, presence: true
  
  
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates :name, 
            presence: true
            
  validates :email, 
            presence: true,
            uniqueness: true, 
            format:{
                with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i
            }

  validates :password, :presence => true,
                   :confirmation => true,
                   :length => {:within => 6..40}
  
end

app/models/vendedor.rb
class Vendedor < ActiveRecord::Base
    validates :nome, presence: true
end

app/controllers/vendedors_controller.rb
class VendedorsController < ApplicationController
  before_action :set_vendedor, only: [:show, :edit, :update, :destroy]

  # GET /vendedors
  def index
    check_user
    @vendedors = Vendedor.all
  end

  # GET /vendedors/1
  def show
    check_user
  end

  # GET /vendedors/new
  def new
    check_user
    @vendedor = Vendedor.new
  end

  # GET /vendedors/1/edit
  def edit
    check_user
  end

  # POST /vendedors
  def create
    @vendedor = Vendedor.new(vendedor_params)

    if @vendedor.save
      redirect_to @vendedor, notice: 'Vendedor was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /vendedors/1
  def update
    if @vendedor.update(vendedor_params)
      redirect_to @vendedor, notice: 'Vendedor was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /vendedors/1
  def destroy
    @vendedor.destroy
    redirect_to vendedors_url, notice: 'Vendedor was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vendedor
      @vendedor = Vendedor.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def vendedor_params
      params.require(:vendedor).permit(:nome)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bancos_helper.rb
module BancosHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/fichas_helper.rb
module FichasHelper
end

app/helpers/lancamentos_helper.rb
module LancamentosHelper
end

app/helpers/locals_helper.rb
module LocalsHelper
end

app/helpers/nf_vendas_helper.rb
module NfVendasHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/vendedors_helper.rb
module VendedorsHelper
end

app/views/vendedors/_form.html.erb
<%= form_for(@vendedor) do |f| %>
  <% if @vendedor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vendedor.errors.count, "error") %> prohibited this vendedor from being saved:</h2>

      <ul>
      <% @vendedor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br>
    <%= f.text_field :nome %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/vendedors/edit.html.erb
<h1>Editing Vendedor</h1>

<%= render 'form' %>

<%= link_to 'Show', @vendedor %> |
<%= link_to 'Back', vendedors_path %>

app/views/vendedors/index.html.erb
<div class="header">
<h1>Vendedores</h1>
</div>
<table id="t01">
  <thead>
    <%= stylesheet_link_tag  'scaffolds', media: 'all', 'data-turbolinks-track' => true %>
    <p id="notice"><%= notice %></p>
    <tr>
      <th>Nome</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vendedors.each do |vendedor| %>
      <tr>
        <td><%= vendedor.nome %></td>
        <td><%= link_to 'Show', vendedor %></td>
        <td><%= link_to 'Edit', edit_vendedor_path(vendedor) %></td>
        <td><%= link_to 'Destroy', vendedor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vendedor', new_vendedor_path %>

app/views/vendedors/new.html.erb
<h1>New Vendedor</h1>

<%= render 'form' %>

<%= link_to 'Back', vendedors_path %>

app/views/vendedors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @vendedor.nome %>
</p>

<%= link_to 'Edit', edit_vendedor_path(@vendedor) %> |
<%= link_to 'Back', vendedors_path %>