config/routes.rb
Rails.application.routes.draw do

  resources :lancamentos
  resources :nf_vendas
  resources :fichas
  resources :bancos
  resources :vendedors
  resources :meio_pagamentos
  resources :customers
  resources :cars
  resources :locals
  resources :sessions, only: [:new, :create, :destroy]
  
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  
  resources :users
  get 'page/index'

  root 'sessions#new'

end

app/models/banco.rb
class Banco < ActiveRecord::Base
    validates :nome, presence: true
end

app/models/car.rb
class Car < ActiveRecord::Base
  belongs_to :local
  
  validates :placa, presence: true
  validates :local, presence: true
  validates :modelo, presence: true
  validates :combustivel, presence: true
  validates :anofabricacao, presence: true
  validates :anomodelo, presence: true
  validates :km, presence: true
  validates :valorvenda, presence: true
end

app/models/customer.rb
class Customer < ActiveRecord::Base
    
    validates :nome, presence: true
    validates :telefone, presence: true
    validates :endereco, presence: true
    validates :cpfcnpj, presence: true
    validates :clioufor, presence: true
    validates :email, presence: true
end

app/models/ficha.rb
class Ficha < ActiveRecord::Base
  belongs_to :Vendedor
  belongs_to :Banco
  belongs_to :Customer
  belongs_to :Cars
  belongs_to :MeioPagamento
  
  validates :Vendedor, presence: true
  validates :Banco, presence: true
  validates :Customer, presence: true
  validates :Cars, presence: true
  validates :MeioPagamento, presence: true
  validates :coef, presence: true
  validates :valfinanceiro, presence: true
  validates :valorparcela, presence: true
  validates :valortotal, presence: true
end

app/models/lancamento.rb
class Lancamento < ActiveRecord::Base
  belongs_to :Ficha
  belongs_to :Customer
  
  validates :status, presence: true
  validates :Customer_id, presence: true
  validates :dtemissao, presence: true
  validates :dtvencimento, presence: true
  validates :valor, presence: true
end

app/models/local.rb
class Local < ActiveRecord::Base
    validates :descricao, presence: true
end

app/models/meio_pagamento.rb
class MeioPagamento < ActiveRecord::Base
    validates :numparcelas, presence: true
    validates :tipo, presence: true
    validates :descricao, presence: true
end

app/models/nf_venda.rb
class NfVenda < ActiveRecord::Base
  belongs_to :Ficha
  
  validates :numerodocumento, presence: true
  validates :valor, presence: true
  validates :desconto, presence: true
  validates :acrescimo, presence: true
  
  
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates :name, 
            presence: true
            
  validates :email, 
            presence: true,
            uniqueness: true, 
            format:{
                with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i
            }

  validates :password, :presence => true,
                   :confirmation => true,
                   :length => {:within => 6..40}
  
end

app/models/vendedor.rb
class Vendedor < ActiveRecord::Base
    validates :nome, presence: true
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_car, only: [:show, :edit, :update, :destroy]

  # GET /cars
  def index
    check_user
    if params[:search] && params[:search]!=''
      @cars = Car.where(modelo: params[:search])
    else
      @cars = Car.all
    end
  end

  # GET /cars/1
  def show
    check_user
  end

  # GET /cars/new
  def new
    check_user
    @car = Car.new
  end

  # GET /cars/1/edit
  def edit
    check_user
  end

  # POST /cars
  def create
    @car = Car.new(car_params)

    if @car.save
      redirect_to @car, notice: 'Car was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /cars/1
  def update
    if @car.update(car_params)
      redirect_to @car, notice: 'Car was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /cars/1
  def destroy
    @car.destroy
    redirect_to cars_url, notice: 'Car was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_car
      @car = Car.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def car_params
      params.require(:car).permit(:status, :local_id, :placa, :modelo, :combustivel, :anofabricacao, :anomodelo, :km, :valorvenda)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bancos_helper.rb
module BancosHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/fichas_helper.rb
module FichasHelper
end

app/helpers/lancamentos_helper.rb
module LancamentosHelper
end

app/helpers/locals_helper.rb
module LocalsHelper
end

app/helpers/nf_vendas_helper.rb
module NfVendasHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/vendedors_helper.rb
module VendedorsHelper
end

app/views/cars/_form.html.erb
<%= form_for(@car) do |f| %>
  <% if @car.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@car.errors.count, "error") %> Não foi possível salvar.</h2>

      <ul>
      <% @car.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :status %><br>
    <%= f.select(:status, 
    options_for_select([["Consignado","1"], ["Vendido","2"], ["Em Negociacao","3"], ["Disponível","4"]], @car.status),
    {include_blank: true})%>
  </div>
  <div class="field">
    <%= f.label :local_id %><br>
    <%= f.select(:local_id, Local.all.collect {|p| [ p.descricao, p.id ]},{include_blank: 'Sem Local'})%>
  </div>
  <div class="field">
    <%= f.label :placa %><br>
    <%= f.text_field :placa %>
  </div>
  <div class="field">
    <%= f.label :modelo %><br>
    <%= f.text_field :modelo %>
  </div>
  <div class="field">
    <%= f.label :combustivel %><br>
    <%= f.select(:combustivel, 
    options_for_select([["Etanol","1"], ["Gasolina","2"], ["Flex","3"]], @car.combustivel),
    {include_blank: true})%>
  </div>
  <div class="field">
    <%= f.label 'Ano de Fabricacao' %><br>
    <%= f.date_select :anofabricacao %>
  </div>
  <div class="field">
    <%= f.label 'Ano do Modelo' %><br>
    <%= f.date_select :anomodelo %>
  </div>
  <div class="field">
    <%= f.label 'Quilometragem' %><br>
    <%= f.text_field :km %>
  </div>
  <div class="field">
    <%= f.label :valorvenda %><br>
    <%= f.text_field :valorvenda %>
  </div>
  <br>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cars/edit.html.erb
<h1>Editing Car</h1>

<%= render 'form' %>

<%= link_to 'Show', @car %> |
<%= link_to 'Back', cars_path %>

app/views/cars/index.html.erb
<div class="header">
  <h1>Carros</h1>
</div>
  <table>
<br/>
  <%= form_tag(cars_path, :method => :get) do %>
  <%= text_field_tag 'search', nil, placeholder: 'Modelo' %>
  <%= submit_tag "Pesquisar" %>
  <% end %>
  <thead>
    <%= stylesheet_link_tag  'scaffolds', media: 'all', 'data-turbolinks-track' => true %>
    <table id="t01">
      <tr>
        <th>Status</th>
        <th>Local</th>
        <th>Placa</th>
        <th>Modelo</th>
        <th>Combustivel</th>
        <th>Anofabricacao</th>
        <th>Andomodelo</th>
        <th>Km</th>
        <th>Valorvenda</th>
        <th colspan="3"></th>
      </tr>
  </thead>
  <tbody>
      <% @cars.each do |car| %>
        <tr>
          <td><%= car.status %></td>
          <td><%= car.local.descricao %></td>
          <td><%= car.placa %></td>
          <td><%= car.modelo %></td>
          <td><%= car.combustivel %></td>
          <td><%= car.anofabricacao %></td>
          <td><%= car.anomodelo %></td>
          <td><%= car.km %></td>
          <td><%= car.valorvenda %></td>
          <td><%= link_to 'Show', car %></td>
          <td><%= link_to 'Edit', edit_car_path(car) %></td>
          <td><%= link_to 'Destroy', car, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
    <% end %>
    </table>
  </tbody>
</table>
<br/>

<%= button_to t('New'), new_car_path,:method => :get %>

app/views/cars/new.html.erb
<html>
	<head>
		<%= stylesheet_link_tag  'scaffolds', media: 'all', 'data-turbolinks-track' => true %>
	</head>
	<body>
		<div class="header">
			<h1>New Car</h1>
		</div>

<%= render 'form' %>

<%= link_to 'Back', cars_path %>
</body>
</html>

app/views/cars/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Status:</strong>
  <%= @car.status %>
</p>

<p>
  <strong>Local:</strong>
  <%= @car.local.descricao %>
</p>

<p>
  <strong>Placa:</strong>
  <%= @car.placa %>
</p>

<p>
  <strong>Modelo:</strong>
  <%= @car.modelo %>
</p>

<p>
  <strong>Combustivel:</strong>
  <%= @car.combustivel %>
</p>

<p>
  <strong>Anofabricacao:</strong>
  <%= @car.anofabricacao %>
</p>

<p>
  <strong>Andomodelo:</strong>
  <%= @car.anomodelo %>
</p>

<p>
  <strong>Km:</strong>
  <%= @car.km %>
</p>

<p>
  <strong>Valorvenda:</strong>
  <%= @car.valorvenda %>
</p>

<%= link_to 'Edit', edit_car_path(@car) %> |
<%= link_to 'Back', cars_path %>

<%= link_to 'Gerar Ficha', new_ficha_path(carro: @car.id) %>